services:
  pg:
    image: postgres:17
    container_name: pg
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_interval: 1s
      start_period: 1m30s
      interval: 30s
      timeout: 10s
      retries: 10
  nats:
    image: nats:2-alpine
    container_name: nats
    restart: unless-stopped
    ports:
      - 4222:4222
      - 8222:8222
    healthcheck:
      test: wget http://localhost:8222/healthz -q -S -O -
      start_interval: 1s
      start_period: 30s
      retries: 10
      timeout: 10s
      interval: 30s
    command: "--port 4222 --http_port 8222 --auth nats -js"
  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: curl --fail http://localhost:9000/minio/health/live || exit 1
      start_interval: 1s
      start_period: 30s
      retries: 10
      timeout: 10s
      interval: 30s
    volumes:
      - miniodata:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9001"
  mailpit:
    image: axllent/mailpit:v1.21
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - mailpitdata:/data
    ports:
      - 8025:8025
      - 1025:1025
    healthcheck:
      test: wget http://localhost:8025/readyz -q -S -O -
      start_interval: 1s
      start_period: 30s
      retries: 10
      timeout: 10s
      interval: 30s
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH: admin:admin
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
volumes:
  pgdata:
  miniodata:
  mailpitdata:
