version: "3"
output: prefixed
interval: 0s
dotenv: [".env"]
vars:
  PWD:
    sh: "pwd"
  BUF_BIN: '{{joinPath .PWD "tools/bin/buf" | toSlash}}{{exeExt}}'
  YAML_FMT_BIN: '{{joinPath .PWD "tools/bin/yamlfmt" | toSlash}}{{exeExt}}'
  GOOSE_BIN: '{{joinPath .PWD "tools/bin/goose" | toSlash}}{{exeExt}}'
  SQLC_BIN: '{{joinPath .PWD "tools/bin/sqlc" | toSlash}}{{exeExt}}'
tasks:
  setup:
    dir: "tools"
    cmds:
      - go mod download
      - go build -o {{shellQuote .BUF_BIN}} github.com/bufbuild/buf/cmd/buf
      - go build -o {{shellQuote .YAML_FMT_BIN}} github.com/google/yamlfmt/cmd/yamlfmt
      - go build -o {{shellQuote .GOOSE_BIN}} github.com/pressly/goose/v3/cmd/goose
      - go build -o {{shellQuote .SQLC_BIN}} github.com/sqlc-dev/sqlc/cmd/sqlc
  fmt:
    cmds:
      - "{{.BUF_BIN}} format -w"
      - "{{.YAML_FMT_BIN}} ."
      - go fmt ./...
  lint:
    cmds:
      - "{{.SQLC_BIN}} vet"
      - "{{.BUF_BIN}} lint"
      # - golangci-lint run
  # build-go:
  #   cmds:
  #     - go build -o {{.BIN}} {{.MAIN}}
  # build:
  #   cmds:
  #     - task: build-go
  generate-db:
    cmds:
      - "{{.SQLC_BIN}} generate"
    sources:
      - sqlc.yaml
      - database/sql/**/*.sql
    generates:
      - database/*.go
  generate-protobuf:
    cmds:
      - "{{.BUF_BIN}} generate"
    sources:
      - buf.yaml
      - buf.gen.yaml
      - api/proto/**/*
    generates:
      - api/gen/**/*.go
  generate:
    cmds:
      - task: generate-db
      - task: generate-protobuf
  # run-go:

  #   cmds:
  #     - task: build-go
  #     - cmd: "{{.BIN}}"
  # run:
  #   deps:
  #     - run-go
  migrate:
    env:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: "{{.POSTGRES_URI}}"
      GOOSE_MIGRATION_DIR: database/sql/schema
    cmds:
      - "{{.GOOSE_BIN}} {{.CLI_ARGS}}"
    requires:
      vars:
        - POSTGRES_URI
  now:
    cmds:
      - echo {{now | date "2006-01-02T15:04:05Z07:00"}}
