# Config file for [Air](https://github.com/air-verse/air) in TOML format
root = "."
tmp_dir = "tmp"

[build]
cmd = "echo 'Generating SQL...'"
full_bin = "task"
args_bin = ["generate-sql"]
include_ext = ["sql"]
exclude_dir = ["tmp"]
include_dir = ["database\\sql", "database/sql"]
include_file = ["sqlc.yaml"]
exclude_unchanged = true
follow_symlink = true
log = "air.log"
send_interrupt = true
kill_delay = 500

[log]
main_only = true
