// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	ulid "github.com/oklog/ulid/v2"
)

type Email struct {
	ID             ulid.ULID
	CreatedAt      time.Time
	Version        int32
	UserID         ulid.ULID
	Value          string
	IsPrimary      bool
	IsVerified     bool
	LastVerifiedAt time.Time
}

type Password struct {
	ID          int64
	CreatedAt   time.Time
	Version     int32
	AbandonedAt pgtype.Timestamptz
	IsActive    bool
	UserID      ulid.ULID
	Value       string
}

type PhoneNumber struct {
	ID             ulid.ULID
	CreatedAt      time.Time
	Version        int32
	UserID         ulid.ULID
	Value          string
	IsPrimary      bool
	IsVerified     bool
	LastVerifiedAt time.Time
}

type RateLimitBucket struct {
	ID             string
	CreatedAt      time.Time
	LastResetAt    time.Time
	Version        int32
	Consumed       int64
	LastConsumedAt pgtype.Timestamptz
}

type ReservedUsername struct {
	Username string
}

type User struct {
	ID                   ulid.ULID
	CreatedAt            time.Time
	Version              int32
	Name                 string
	Username             string
	Dob                  pgtype.Date
	Bio                  pgtype.Text
	Website              pgtype.Text
	Location             pgtype.Text
	AvatarPath           pgtype.Text
	BannerPath           pgtype.Text
	LastActiveAt         time.Time
	PrimaryEmailID       ulid.ULID
	PrimaryPhoneNumberID ULIDValue
	IsMfaEnabled         bool
	IsBot                bool
	ProfileLocked        bool
	ShowDob              bool
}

type VerificationToken struct {
	Token         string
	ID            int64
	CreatedAt     time.Time
	ExpireAt      time.Time
	UserID        ulid.ULID
	EmailID       ULIDValue
	PhoneNumberID ULIDValue
	Otp           string
}
