// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: passwords.sql

package database

import (
	"context"

	ulid "github.com/oklog/ulid/v2"
)

const createPassword = `-- name: CreatePassword :exec
INSERT INTO
    "passwords" ("id", "is_active", "user_id", "value")
VALUES
    ($1, $2, $3, $4)
`

type CreatePasswordParams struct {
	ID       ulid.ULID
	IsActive bool
	UserID   ulid.ULID
	Value    string
}

func (q *Queries) CreatePassword(ctx context.Context, arg *CreatePasswordParams) error {
	_, err := q.db.Exec(ctx, createPassword,
		arg.ID,
		arg.IsActive,
		arg.UserID,
		arg.Value,
	)
	return err
}
