// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: phone_numbers.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	ulid "github.com/oklog/ulid/v2"
)

const createPhoneNumber = `-- name: CreatePhoneNumber :exec
INSERT INTO
    "phone_numbers" (
        "id",
        "user_id",
        "value",
        "is_primary",
        "is_verified",
        "last_verified_at"
    )
VALUES
    ($1, $2, $3, $4, $5, $6)
`

type CreatePhoneNumberParams struct {
	ID             ulid.ULID
	UserID         ulid.ULID
	Value          string
	IsPrimary      bool
	IsVerified     bool
	LastVerifiedAt pgtype.Timestamptz
}

func (q *Queries) CreatePhoneNumber(ctx context.Context, arg *CreatePhoneNumberParams) error {
	_, err := q.db.Exec(ctx, createPhoneNumber,
		arg.ID,
		arg.UserID,
		arg.Value,
		arg.IsPrimary,
		arg.IsVerified,
		arg.LastVerifiedAt,
	)
	return err
}

const isPhoneNumberAvailable = `-- name: IsPhoneNumberAvailable :one
SELECT
    NOT EXISTS (
        SELECT
            1
        FROM
            "phone_numbers"
        WHERE
            "value" = $1
            AND "is_verified"
    )
`

func (q *Queries) IsPhoneNumberAvailable(ctx context.Context, value string) (bool, error) {
	row := q.db.QueryRow(ctx, isPhoneNumberAvailable, value)
	var not_exists bool
	err := row.Scan(&not_exists)
	return not_exists, err
}
