// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateRateLimitBucket(ctx context.Context, arg *CreateRateLimitBucketParams) error
	GetRateLimitBucket(ctx context.Context, id string) (RateLimitBucket, error)
	IsUsernameAvailable(ctx context.Context, username string) (pgtype.Bool, error)
	UpdateRateLimitBucket(ctx context.Context, arg *UpdateRateLimitBucketParams) (RateLimitBucket, error)
}

var _ Querier = (*Queries)(nil)
