// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const isUsernameAvailable = `-- name: IsUsernameAvailable :one
SELECT
    NOT EXISTS (
        SELECT
            1
        FROM
            "users"
        WHERE
            "users"."username" = $1
    )
    AND NOT EXISTS (
        SELECT
            1
        FROM
            "reserved_usernames"
        WHERE
            "reserved_usernames"."username" = $1
    ) AS "is_username_available"
`

func (q *Queries) IsUsernameAvailable(ctx context.Context, username string) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, isUsernameAvailable, username)
	var is_username_available pgtype.Bool
	err := row.Scan(&is_username_available)
	return is_username_available, err
}
