// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO
    "users" ("name")
VALUES
    ($1)
`

func (q *Queries) CreateUser(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, createUser, name)
	return err
}
