// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: verification_tokens.sql

package database

import (
	"context"
	"time"

	ulid "github.com/oklog/ulid/v2"
)

const createVerificationToken = `-- name: CreateVerificationToken :exec
INSERT INTO
    "verification_tokens" (
        "token",
        "id",
        "expire_at",
        "user_id",
        "email_id",
        "phone_number_id",
        "otp"
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7)
`

type CreateVerificationTokenParams struct {
	Token         string
	ID            ulid.ULID
	ExpireAt      time.Time
	UserID        ulid.ULID
	EmailID       ULIDValue
	PhoneNumberID ULIDValue
	Otp           string
}

func (q *Queries) CreateVerificationToken(ctx context.Context, arg *CreateVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, createVerificationToken,
		arg.Token,
		arg.ID,
		arg.ExpireAt,
		arg.UserID,
		arg.EmailID,
		arg.PhoneNumberID,
		arg.Otp,
	)
	return err
}
